### ISSUE TITLE
这样.snippet怎么使用

### ISSUE THREAD

**Issue by bingbaicai** [Du23456/Quantumult-X#6]
这样.snippet怎么使用
您首页的教程有点简单，菜鸟看不明白😂
谢谢

**Comment by bingbaicai** [comment]
搞定了
不过好像JD的没效果啊 亲

**Comment by Du23456** [comment]
先拷贝后缀.snippet的链接
打开Quantumult X，长按顶部粉色的按钮（类似一支笔）
出现资源列表后点击右上角的类似🔗的图标
在资源路径里粘贴刚才拷贝的链接，资源标签随便写
点击右上角的“勾”即可

**Comment by Du23456** [comment]
仓库有些陈旧资源没删，能用就凑合用，没用就无视
V2文件夹成功率比V1高

1️⃣记得一直开着代理用有广告的App
2️⃣App有缓存，建议卸载重装

规则均搬运，可根据页面署名去作者仓库

**Comment by Du23456** [comment]
JD要12.4.3及以下才能去广告
